import type { NextPage } from 'next';
import Head from 'next/head';

const Dashbord: NextPage = () => (
  <div>
    <Head>
      <title>Dashboard</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main>
      <h1>Hi :D</h1>
    </main>
  </div>
);

export default Dashbord;
